# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: image_classification.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aimage_classification.proto\"8\n\nPrediction\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x63lase\x18\x02 \x01(\t\x12\r\n\x05score\x18\x03 \x01(\x02\"\"\n\x0cImageRequest\x12\x12\n\nimage_path\x18\x01 \x01(\t\"1\n\rImageResponse\x12 \n\x0bpredictions\x18\x01 \x03(\x0b\x32\x0b.Prediction2E\n\x13ImageClassification\x12.\n\rClassifyImage\x12\r.ImageRequest\x1a\x0e.ImageResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'image_classification_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PREDICTION']._serialized_start=30
  _globals['_PREDICTION']._serialized_end=86
  _globals['_IMAGEREQUEST']._serialized_start=88
  _globals['_IMAGEREQUEST']._serialized_end=122
  _globals['_IMAGERESPONSE']._serialized_start=124
  _globals['_IMAGERESPONSE']._serialized_end=173
  _globals['_IMAGECLASSIFICATION']._serialized_start=175
  _globals['_IMAGECLASSIFICATION']._serialized_end=244
# @@protoc_insertion_point(module_scope)
